receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318
      grpc:
        endpoint: 0.0.0.0:4317

processors:
  batch:

exporters:
  otlp/jaeger:
    endpoint: jaeger-all-in-one:4317
    tls:
      insecure: true

  clickhouse/traces:
    endpoint: tcp://clickhouse-server:9000?username=default&password=admin
    database: default
    traces_table_name: otel_traces

service:
  pipelines:
    # metrics:
    #   receivers: [otlp]
    #   processors: [batch]
    #   exporters: [datadog]

    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/jaeger, clickhouse/traces]

    # logs:
    #   receivers: [otlp]
    #   processors: [batch]
    #   exporters: [datadog]
